### PR TITLE
Drop hardcoded, specific package versions

### LINKED ISSUE #383: replace giant version info hash with something more sane
Related to https://github.com/chef-cookbooks/mysql/pull/382

@tas50 @iennae can one of you take a look at this?

### LINKED ISSUE #436: ubuntu 16.04 -> mysql 5.7 -> error
### Cookbook version
8.0.1

### Chef-client version
12

### Platform Details
ubuntu 16.04 xenial

### Output

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'mysql_service[default]'
==> default:     
==> default: ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     mysql_server_installation_package[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-server-5.7] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default:     ---- Begin output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
==> default:     STDOUT: Reading package lists...
==> default:     Building dependency tree...
==> default:     Reading state information...
==> default:     STDERR: E: Version '5.7.12-0ubuntu1.1' for 'mysql-server-5.7' was not found
==> default:     ---- End output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
==> default:     Ran apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 returned 100
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/blabla/recipes/db_mysql.rb
==> default:     
==> default:       5: mysql_service 'default' do
==> default:       6:   version '5.7'
==> default:       7:   bind_address '0.0.0.0'
==> default:       8:   port '3306'
==> default:       9:   data_dir '/data/mysql'
==> default:      10:   initial_root_password root_password
==> default:      11:   action [:create, :start]
==> default:      12: end
```

### LINKED ISSUE #470: No candidate version available for mysql-community-server on CentOS 6.8
### Cookbook version
8.0.2

### Chef-client version
12.13.30

### Platform Details
CentOS 6.8 

### Scenario:
In my recipe, I was trying to do a simple install and start of MySQL service, code as below:

`mysql_service 'default' do
    port '3306'
    version '5.6'
    bind_address '0.0.0.0'
    initial_root_password 'MyPass'
    action [:create, :start]
end`

### Steps to Reproduce:
Using above codes

### Expected Result:
MySQL gets installed and started.

### Actual Result:
Error shows no candidate for mysql-community-server was found:

 * mysql_service[test] action create
    * mysql_server_installation_package[test] action install
      * yum_package[mysql-community-server] action install
        * No candidate version available for mysql-community-server
        ================================================================================
        Error executing action `install` on resource 'yum_package[mysql-community-server]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for mysql-community-server

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb

         17:       package package_name do
         18:         version package_version if package_version
         19:         options package_options if package_options
         20:         notifies :install, 'package[perl-Sys-Hostname-Long]', :immediately if platform_family?('suse')
         21:         notifies :run, 'execute[Initial DB setup script]', :immediately if platform_family?('suse')
         22:         action :install
         23:       end
         24:

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb:17:in `block in <class:MysqlServerInstallationPackage>'

        yum_package("mysql-community-server") do
          package_name "mysql-community-server"
          action [:install]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "MyCookbook"
          flush_cache {:before=>false, :after=>false}
          version "5.6.29-2.el6"
        end

        Platform:
        ---------
        x86_64-linux

### LINKED ISSUE #471: New ubuntu mysql server version for 5.7
### Cookbook version
latest

### Chef-client version
12.13.37

### Platform Details
Ubuntu 16.04

### Scenario:
Install mysql server 5.7

### Steps to Reproduce:
Install mysql server 5.7 on an ubuntu xenial base system

### Expected Result:
Mysql Server 5.7 gets installed

### Actual Result:
Install fails with: "Version '5.7.13-0ubuntu0.16.04.2' for 'mysql-server-5.7' was not found"

Is there a way to overwrite the default package version? And if there isn't, why not? If PR is welcome i could add an extra prop, maybe "explicit_package_version" or similar.

### LINKED ISSUE #472: New MySQL version for Ubuntu 14.04
### Cookbook version
8.0.2

### Chef-client version
12.10.24

### Platform Details
Ubuntu 14.04

### Scenario:
Install MySQL 5.5

### Steps to Reproduce:
```
mysql_service 'default' do
  initial_root_password 'password'
  action [:create, :start]
  socket '/var/run/mysqld/mysqld.sock'
end
```

### Expected Result:
MySQL to be installed successfully

### Actual Result:
```
==> default: [2016-09-14T12:21:33+00:00] ERROR: mysql_service[default] (myserver::mysql line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: mysql_server_installation_package[default] (/tmp/vagrant-chef/8669fe112c737e422c3491de9a534503/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-server-5.5] (/tmp/vagrant-chef/8669fe112c737e422c3491de9a534503/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.5=5.5.50-0ubuntu0.14.04.1 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: STDERR: E: Version '5.5.50-0ubuntu0.14.04.1' for 'mysql-server-5.5' was not found
==> default: ---- End output of apt-get -q -y install mysql-server-5.5=5.5.50-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.5=5.5.50-0ubuntu0.14.04.1 returned 100
```

### LINKED ISSUE #476: Is it sane to hardcode package versions within the cookbook?
Following on from the spate of bugs opened as a result of the MySQL security fixes that went out over the last few days, I'd like to question the logic of why each package version is hard coded to a specific package? I mentioned this in the 16.04  bug report specifically, but thought it wise to open a specific ticket to discuss this. 

It would seem absolutely sensible to give users the option to pin to a specific package via a property of the resource, but surely the default behaviour should be to use the version offered up by the operating system's package manager?

I noticed in another thread that someone has worked around this by passing in `:package_version ''` to their mysql_server resource, but that doesn't help when other cookbooks utilise it in their own manner (eg the `mysql2_chef_gem` resource calling `mysql_client`)

### LINKED ISSUE #479: Failure on Debian 8.4, mismatched version number
### Cookbook version
8.0.3

### Chef-client version
12.13.37

### Platform Details
Debian 8.4 (AWS ami-98e114f8) 

### Scenario:
Trying to install MySQL 5.5

### Steps to Reproduce:
mysql_service db_dbname do
  port '3306'
  version '5.5'
  initial_root_password db_root_password
  action [:create, :start]
end

### Expected Result:
Running MySQL daemon

### Actual Result:
The mysql-server package is not retrieved.   The error log has scrolled out of my life, but the problem was that the wrong minor version is used.
In helpers.rb, line 183, the version is specified as 5.5.49-0.  
That version is not available via the apt package manager. 
I changed the number to 5.5.52-0 and it worked.

Setting the version in the lwrp only works for the major number.  It would have been more convenient to be able to set the minor number there as well.
Maybe a fallback to the default major version number (i.e. 5.5)  in cases where the package is not found?

### LINKED ISSUE #482: Update mysql version for amazon linux
### Cookbook version
[8.0.4]

### Chef-client version
[12.11]

### Platform Details
[Amazon linux]

### Scenario:
[I was try to install mysql version 5.6.33-2, it was going on 5.6.31.-2]

### Steps to Reproduce:
[use mysql cookbook and try to install on amazon linux]

### Expected Result:
[That should install mysql server 5.6.33-2]

### Actual Result:
[That is installing mysql server 5.6.31.-2]

### LINKED ISSUE #484: New package version for Ubuntu 16.04.1 LTS
### Cookbook version
8.0.4

### Chef-client version
12.15.19

### Platform Details
Ubuntu 16.04.1 LTS - AWS EC2

### Scenario:
Install mysql-client-5.7

### Steps to Reproduce:
use the default mysql_client library from the cookbook to try and install the client

### Expected Result:
mysql client 5.7 installs

### Actual Result:
Chef client run fails on version 5.7.15.  looking in apt-cache for mysql-client-5.7 shows version 5.7.16 available.

```
STDERR: E: Version '5.7.15-0ubuntu0.16.04.1' for 'mysql-client-5.7' was not found
    ---- End output of apt-get -q -y install mysql-client-5.7=5.7.15-0ubuntu0.16.04.1 ----
```

```
$ apt-cache policy mysql-client-5.7
mysql-client-5.7:
  Installed: (none)
  Candidate: 5.7.16-0ubuntu0.16.04.1
```

### PR DESCRIPTION
**Pull request by jeffbyrnes**
### Description

This removes the hardcoded package versions, and the default behavior of using these hardcoded versions, in favor of a less fragile method of using the `major_version` to install MySQL.

An operator may still specify a `package_version` if they wish.

### Issues Resolved

* Fixes #484
* Fixes #482
* Fixes #479
* Fixes #476 
* Fixes #472
* Fixes #471
* Fixes #470
* Fixes #436
* Fixes #383

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by flatrocks** [comment]
Tests you may find useful:

1) **spec/spec_helper.rb**
I added a default platform and version.  Any valid values will work, they're just needed to avoid warnings when running tests in spec/package_version_spec.rb.
```ruby
RSpec.configure do |config|
  config.platform = 'ubuntu'
  config.version = '16.04'
  ...
```

2) **spec/package_version_spec.rb** (new file)
```ruby
require 'spec_helper'
require_relative "../libraries/helpers"

describe 'mysql_test::package_version' do
  let(:chef_run) do
    ChefSpec::ServerRunner.new() do |node|
      # Stubs avoid dependency on platform & version for this test
      allow(MysqlCookbook::HelpersBase).to receive(:default_client_package_name).and_return 'the_default_client_package_name'
      allow(MysqlCookbook::HelpersBase).to receive(:default_server_package_name).and_return 'the_default_server_package_name'
    end.converge(described_recipe)
  end
  describe "the package_version property" do
    context 'when it is not set' do
      it 'no default value is passed to the install package' do
        expect(chef_run).to install_mysql_client_installation_package('default').with(
          package_version: nil
        )
      end
      it 'no default value is passed to the mysql_server_installation_package' do
        expect(chef_run).to install_mysql_server_installation_package('default').with(
          package_version: nil
        )
      end
    end
    context 'when it is set' do
      it 'is passed to the mysql_client_installation_package' do
        expect(chef_run).to install_mysql_client_installation_package('with a specified package version').with(
          package_version: 'the-specified-package_version'
        )
      end
      it 'is passed to the mysql_server_installation_package' do
        expect(chef_run).to install_mysql_server_installation_package('with a specified package version').with(
          package_version: 'the-specified-package_version'
        )
      end
    end
  end
end
```

3) **test/cookbooks/mysql_test/recipes/package_version.rb** (new file)
```ruby
mysql_client_installation_package 'default' do
  action :create
end

mysql_client_installation_package 'with a specified package version' do
  package_version 'the-specified-package_version'
  action :create
end

mysql_server_installation_package 'default' do
  action :install
end

mysql_server_installation_package 'with a specified package version' do
  package_version 'the-specified-package_version'
  action :install
end
```

Results:
```
prompt$   rspec spec/package_version_spec.rb

mysql_test::package_version
  the package_version property
    when it is not set
      no default value is passed to the install package
      no default value is passed to the mysql_server_installation_package
    when it is set
      is passed to the mysql_client_installation_package
      is passed to the mysql_server_installation_package

...
```

**Comment by tas50** [comment]
Thank you so much for putting this together. We really needed to back this out so we could get some stability here.

File: libraries/helpers.rb [hunk 1]
```diff
@@ -147,54 +147,6 @@ def default_server_package_name
...
-      return '5.6.31-0ubuntu0.14.04.2' if major_version == '5.6' && trusty?
-      return '5.7.15-0ubuntu0.16.04.1' if major_version == '5.7' && xenial?
-
-      # suse
-      return '5.6.30-2.20.2' if major_version == '5.6' && opensuse?
-      return '5.6.30-16.2' if major_version == '5.6' && opensuseleap?
-
-      raise "No package version found for version #{major_version} on #{node['platform']} #{node['platform_version']}. Aborting."
-    end
-
```
Comment (lamont-granquist) [inline libraries/helpers.rb]: ❤️

**Comment by jeffbyrnes** [comment]
@tas50 thanks for getting this out so quickly!

**Comment by wilb** [comment]
A million thanks from here too :+1:
